### ISSUE TITLE
Where is RootView?

### ISSUE THREAD

**Issue by mercurio** [flamejs/flame.js#214]
I'm trying to sync up to the current version of Flame but it appears that RootView is no longer available. Is there a new way to start a Flame app? Are there any updated examples anywhere? It seems like all of the jsfiddle examples don't work either, both Handlebars and RootView are reported missing.

**Comment by ctimmerm** [comment]
A while ago, Flame was updated to work with Ember 1.x, which means that handlebars is now a separate dependency. I've updated the starter kit (https://github.com/flamejs/flame-starter-kit) to the latest version of Flame. The starter kit also includes all required dependencies (Ember, Handlebars, jQuery).

Flame.RootView has been removed, simply because there is no need for it anymore. Any Flame.View can be at the root of a view hierarchy.

Do note that a patched version of Ember is required at this point (it's included in the starter kit, reason explained here: https://github.com/flamejs/flame-starter-kit#important).

Let me know if you have any other questions.
